### ISSUE TITLE
GOPATH environment not set

### ISSUE THREAD

**Issue by pbnj** [nortonlifelock/aegis#18]
Why does a compiled binary have a dependency on language specific environment variables, like `$GOPATH`?

My use-case involves building aegis binary in a `golang:1.13` container image and copying the static binary to a scratch container (i.e. [builder pattern](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#use-multi-stage-builds)).

Then running `$ docker run --rm aegis:dev  --help` throws `GOPATH environment variable not set` error. The workaround for me is to pass an environment variable to the container: `docker run -e GOPATH=/go aegis:dev --help`. 

I see that this is being used to construct the "default path" for the config file `app.json`, but this approach is less than ideal.

If `cpath` and `config` are required flags for `aegis` to run, then ideally that's enough.
If you really want to set a default path, it should be documented that in the absence of the required flags, `aegis` will attempt to look in a language-agnostic path, like `$HOME/.config/aegis/aegis.json` or `$HOME/aegis.json`.

**Comment by benjivesterby** [comment]
What error are you getting? Aegis has never had a dependency on GOPATH.

**Comment by benjivesterby** [comment]
NVM, I found it. Looks like it was added in in the init code this past week. That shouldn't be there.

**Comment by benjivesterby** [comment]
@ryan-everhart Why is the init stuff being setup inside of Aegis in the first place? It's now running commands against the system with exec.Command and has a hardcoded dependency on GOPATH now as well. These things should not be the responsibility of Aegis.

**Comment by ryan-everhart** [comment]
@benjivesterby the goal was to have the initialization processes included in the aegis command. It seems more user friendly to have an "aegis init" command instead of an entirely separate repo that needs to be pulled and installed.

Agreed that there should not be a GOPATH dependency in the code. I will work on removing that

**Comment by ryan-everhart** [comment]
The dependency on GOPATH has been removed. The installation process will now use the current working directory by default, but flags have been added to allow redirection at any time if desired.
